field: 67f553d8-602a-49f3-a4ef-8910c7034fa9 # Karriere Detail Matrix
fieldLayouts:
  20e6c364-e6f0-4117-afac-c4e1402437ba:
    tabs:
      -
        elements:
          -
            fieldUid: 04c1254a-9e0e-4e41-94e7-9422d9b350f2 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  04c1254a-9e0e-4e41-94e7-9422d9b350f2: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Wunderlab.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: contentText
name: 'Content Text'
sortOrder: 1
