columnSuffix: hebyroyq
contentColumnType: text
fieldGroup: cf094fa0-aec3-459e-a67b-5531e87438fb # global
handle: headerendscripts
instructions: 'Code-Schnipsel, welches vor Head Ende Tag in die Webseite eingebaut wird'
name: 'Scripts Head End'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
