columnSuffix: jnzmexrc
contentColumnType: text
fieldGroup: 3ce9e77b-5b04-4678-a633-58827f84519a # Common
handle: htmlCode
instructions: ''
name: 'HTML Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
