columnSuffix: null
contentColumnType: string
fieldGroup: 3ce9e77b-5b04-4678-a633-58827f84519a # Common
handle: imagesingle
instructions: ''
name: Bild
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
