columnSuffix: null
contentColumnType: string
fieldGroup: cf094fa0-aec3-459e-a67b-5531e87438fb # global
handle: imgWebappicon
instructions: "Webapp Icons ( favicons / apple-touch-icon / msapplication ) \r\n\r\n512x512Pixel (Format PNG)"
name: 'Webapp Icon'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
