columnSuffix: zfjfaaao
contentColumnType: string
fieldGroup: cf094fa0-aec3-459e-a67b-5531e87438fb # global
handle: navigationLevel
instructions: "Bitte Anzahl der Navigationsebenen eintragen.\r\n1 = 1  Ebene (Hauptnavigation)\r\n2 = 2 Ebenen (Hauptnavigation + 1 Subnavigation)\r\n..."
name: 'Navigation Level'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '1'
        -
          - value
          - '1'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
