field: 7fd956ab-cc81-45a1-9446-b3fc682b2c52 # Image Item
fieldLayouts:
  58364650-b753-4549-bba0-dce20d9223ef:
    tabs:
      -
        elements:
          -
            fieldUid: 97c92a4d-6011-455f-a7c2-1f8752e0c8b7 # Preview Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 504c2068-558e-42cb-85dd-d457605fef2e # Gallery Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 90065eb5-9fa8-457d-b9e4-b22802c1b826 # Info Text Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  97c92a4d-6011-455f-a7c2-1f8752e0c8b7: # Preview Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: previewImage
    instructions: "Optional!\r\nWird kein Bild hinzugefügt, wird das Galerie Bild benutzt."
    name: 'Preview Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Vorschaubild hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  504c2068-558e-42cb-85dd-d457605fef2e: # Gallery Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galleryImage
    instructions: ''
    name: 'Gallery Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Galeriebild hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  90065eb5-9fa8-457d-b9e4-b22802c1b826: # Info Text Image
    columnSuffix: null
    contentColumnType: string(280)
    fieldGroup: null
    handle: infoTextImage
    instructions: ''
    name: 'Info Text Image'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 70
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
