field: 259d3b3c-2946-45c5-955b-c96f1d34e90f # Social Media Liste
fieldLayouts:
  8fec98bb-3ac0-4af8-8ec6-4efa389a41ed:
    tabs:
      -
        elements:
          -
            fieldUid: 2031484f-2837-419b-b3aa-984941cb7431 # Media Liste Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 519c5877-0163-4300-aeea-fa724ef490fa # Media Liste Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a338d70-4dfc-4ea5-b2c9-32494fcd7f60 # Media Liste Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3a338d70-4dfc-4ea5-b2c9-32494fcd7f60: # Media Liste Link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: mediaListeLink
    instructions: ''
    name: 'Media Liste Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  519c5877-0163-4300-aeea-fa724ef490fa: # Media Liste Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: mediaListeText
    instructions: ''
    name: 'Media Liste Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2031484f-2837-419b-b3aa-984941cb7431: # Media Liste Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: mediaListeIcon
    instructions: ''
    name: 'Media Liste Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:4ade9959-165d-46c7-8053-b22070538ce5' # images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
