currLabel: Dateien
customIcon: null
enabled: true
handle: assets
icon: assets
layout: eb1f8a0c-76c5-48cc-9672-7044f646159e # Default
newWindow: false
order: 4
prevLabel: Dateien
prevUrl: assets
type: ''
url: assets
