currLabel: SEO
customIcon: null
enabled: true
handle: seo
icon: /usr/www/users/devswu/starter/starter-entwicklung/vendor/ether/seo/src/icon-mask.svg
layout: eb1f8a0c-76c5-48cc-9672-7044f646159e # Default
newWindow: false
order: 5
prevLabel: SEO
prevUrl: seo
type: ''
url: seo
