currLabel: Einstellungen
customIcon: null
enabled: true
handle: settings
icon: settings
layout: eb1f8a0c-76c5-48cc-9672-7044f646159e # Default
newWindow: false
order: 9
prevLabel: Einstellungen
prevUrl: settings
type: ''
url: settings
