currLabel: Forms
customIcon: null
enabled: true
handle: wheelform
icon: /usr/www/users/devswu/starter/starter-entwicklung/vendor/xpertbot/craft-wheelform/src/icon-mask.svg
layout: eb1f8a0c-76c5-48cc-9672-7044f646159e # Default
newWindow: false
order: 7
prevLabel: Forms
prevUrl: wheelform
type: ''
url: wheelform
